* The dependencies which are use for the auth project:-

*1) org.clojure/java.jdbc:-* A Clojure interface to SQL databases via JDBC.
clojure.java.jdbc provides a simple abstraction for CRUD (create, read,
update, delete) operations on a SQL database, along with basic transaction
support. Basic DDL operations are also supported (create table, drop table,
access to table metadata).

*2) com.h2database/h2:-* H2 database is a JAVA library implemented a SQL database engine.

*3) hikari-cp:-* It is a library that manages database connection pools.

*4) ch.qos.logback/logback-classic:-* It is a logging library for Java. Logback-classic natively implements the SLF4J API so that you can readily switch back and forth between logback and other logging frameworks such as log4j or java.util.logging (JUL).
The logback-access module integrates with Servlet containers, such as Tomcat and Jetty, to provide HTTP-access log functionality.

*5) buddy/buddy-sign:-* Buddy sign module is dedicated to provide a high level abstraction for web ready message signing and encryption. It can be used for several purposes:
    + You can serialize and sign or encrypt a user ID for unsubscribing of newsletters into URLs. This way you don’t need to generate one-time tokens and store them in the database.
    + Same thing with any kind of activation link for accounts and similar things.
    + Signed or encrypted objects can be stored in cookies or other untrusted sources which means you don’t need to have sessions stored on the server, which reduces the number of necessary database queries.
    + Signed information can safely do a roundtrip between server and client in general which makes them useful for passing server-side state to a client and then back.
    + Safely send and receve signed or encrypted messages between components or microservices.
    + Self contained token generation for use with completely stateless token based authentication.

*6) buddy/buddy-hashers:-* buddy-hashers provides a collection of secure password hashers with lightweight and extensible abstraction for build powerfull password authentication processes.

*7) ring-server:-* A library for starting a web server to serve a Ring handler with sensible default options and environment variable overrides.

* :profiles {:dev ........}
*1) Lein-Ring plugin:-* Lein-Ring is a Leiningen plugin that automates common Ring tasks.It provides commands to start a development web server, and to turn a Ring handler into a standard war file.
