** How to run xtnt-auth project?
+ Download [[https://h2database.com/html/main.html][H2 database]] and unzip the file
+ In H2 folder, and then within bin folder, you will find a *.jar file* ~(h2-1.4.197.jar)~.
+ Double click on the jar file and it will automatically open the login page in the browser.
+ In the login diolouge box, you need to choose ~Generic H2(server)~ and then click on save.
+ No ~username~ and ~password~ is needed.
+ Click on connect option and it will make the server ready to connect with your application.
+ In case (for ex - Linux based systems) there's an issue wherein a message appears in the login
dialogue box that you're unable to connect, create a new database in the running H2 application and
set username and password.
+ Also for the above issue, change the JDBC URL ~jdbc:h2:./test~ of the login page. Mention username
and password as that for the above created database.
+ In case you have created a new database with a different set of username and password, edit the
~datasource.clj~ file to change the ~:username~ and ~:password~ values within ~datasource-options~. 
+ Now from shell or terminal run ~lein run~ and wait for some time. It will automatically open your
browser and run your application on ~port 4000~.
+ On the left hand side you will find the list of the tables which we have created from ~dbtable.clj~
file.
+ If you want to delete the table in order to restart your application, you need to run the command
~DROP TABLE TABLE-NAME;~ for example ~DROP TABLE APPLICATION;~ and click on *Run selected* option.
